### ISSUE TITLE
feat: projects showcase

### ISSUE THREAD

**Issue by elianiva** [wrideveloper/wri-dev#15]
the layout should look something like this, more details on figma
it should show the project name and brief overview on hover

![image](https://github.com/wrideveloper/wri-dev/assets/51877647/4de4984a-02a3-4191-a3c0-1b60edae15e5)

**Comment by alizul01** [comment]
when click the and more, is there any reference of it?

**Comment by elianiva** [comment]
yes, ideally it should go to the page where it gives the project overview
kinda like readme but instead of going into technical detail, it should describe the general overview of the project, think of it like a mini blog post for the project

**Comment by elianiva** [comment]
ditched this idea for now since we don't really have anything, superseded by #51
